// const path = require('path')
// const extraNodeModules = {
//   example '../../../../engine_autogenerated' resolves /Users/yeewong/dev/busdue5/inton/prirepo/theapp/engine_autogenerated
//   engine_autogenerated: path.resolve(__dirname + '../../../../../../../engine_autogenerated'),
//   appModules: path.resolve(__dirname + '../../../../../../../demo-modules'),
// }
//
// const watchFolders = [
//   path.resolve(__dirname + '../../../../../../../engine_autogenerated'),
//   path.resolve(__dirname + '../../../../../../../demo-modules'),
// ];

module.exports = {
  resolver: {
    sourceExts: ['ts', 'tsx', 'js', 'json'],
    platforms: ['ios', 'android'],
    // extraNodeModules,
  },
  // watchFolders,
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
}
